In [2]:
import pandas as pd

In [3]:
online_retail_store_df = pd.read_excel('C:/Users/91706/Downloads/online+retail+ii/online_retail_II.xlsx')

In [34]:
print(online_retail_store_df.shape)
print(online_retail_store_df.dtypes)

(525461, 8)
Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID           float64
Country                object
dtype: object

In [35]:
online_retail_store_df.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [60]:
null_df = online_retail_store_df[online_retail_store_df['Description'].isna()]

In [61]:
null_df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
524730,538141,22218,NaN,2,2010-12-09 15:58:00,0.0,NaN,United Kingdom
524731,538143,84534B,NaN,1,2010-12-09 15:58:00,0.0,NaN,United Kingdom
525231,538159,21324,NaN,-18,2010-12-09 17:17:00,0.0,NaN,United Kingdom
525232,538158,20892,NaN,-32,2010-12-09 17:17:00,0.0,NaN,United Kingdom
525233,538160,20956,NaN,288,2010-12-09 17:18:00,0.0,NaN,United Kingdom

In [57]:
online_retail_store_df[online_retail_store_df['StockCode']==18010]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
976,489545,18010,ASSORTED FRAGRANCE BATH CONFETTI,6,2009-12-01 12:22:00,0.42,17804.0,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.00,NaN,United Kingdom
5341,489856,18010,ASSORTED FRAGRANCE BATH CONFETTI,1,2009-12-02 14:36:00,0.83,NaN,United Kingdom
5618,489857,18010,ASSORTED FRAGRANCE BATH CONFETTI,1,2009-12-02 14:43:00,0.83,NaN,United Kingdom
8385,490074,18010,ASSORTED FRAGRANCE BATH CONFETTI,6,2009-12-03 14:39:00,0.83,NaN,United Kingdom
26509,491662,18010,ASSORTED FRAGRANCE BATH CONFETTI,24,2009-12-13 11:16:00,0.42,15169.0,United Kingdom
32790,492075,18010,ASSORTED FRAGRANCE BATH CONFETTI,5,2009-12-15 13:21:00,0.42,17596.0,United Kingdom
41701,492811,18010,ASSORTED FRAGRANCE BATH CONFETTI,10,2009-12-20 13:01:00,0.42,17085.0,United Kingdom
42423,492993,18010,ASSORTED FRAGRANCE BATH CONFETTI,2,2009-12-21 15:54:00,0.42,14819.0,United Kingdom
73431,496017,18010,ASSORTED FRAGRANCE BATH CONFETTI,9,2010-01-28 13:23:00,0.42,16326.0,United Kingdom
80588,496790,18010,NaN,-2,2010-02-03 16:45:00,0.00,NaN,United Kingdom

In [36]:
print("Full duplicates:", online_retail_store_df.duplicated().sum())
print("Duplicate Invoices:", online_retail_store_df.duplicated(subset=['Invoice']).sum())

Full duplicates: 6865
Duplicate Invoices: 496645

In [37]:
online_retail_store_df[['Quantity', 'Price']].describe()

            Quantity          Price
count  525461.000000  525461.000000
mean       10.337667       4.688834
std       107.424110     146.126914
min     -9600.000000  -53594.360000
25%         1.000000       1.250000
50%         3.000000       2.100000
75%        10.000000       4.210000
max     19152.000000   25111.090000

In [38]:
print("Positive Quantity (order_item_created):", (online_retail_store_df['Quantity'] > 0).sum())
print("Negative Quantity (order_item_cancelled):", (online_retail_store_df['Quantity'] < 0).sum())
print("Zero Quantity:", (online_retail_store_df['Quantity'] == 0).sum())

Positive Quantity (order_item_created): 513135
Negative Quantity (order_item_cancelled): 12326
Zero Quantity: 0

In [39]:
print("Negative prices:", (online_retail_store_df['Price'] < 0).sum())
print("Zero prices:", (online_retail_store_df['Price'] == 0).sum())

Negative prices: 3
Zero prices: 3687

In [45]:
online_retail_store_df['InvoiceDate'].dt.year.value_counts()

InvoiceDate
2010    480233
2009     45228
Name: count, dtype: int64

In [46]:
online_retail_store_df['Country'].value_counts().head(10)

Country
United Kingdom     485852
EIRE                 9670
Germany              8129
France               5772
Netherlands          2769
Spain                1278
Switzerland          1187
Portugal             1101
Belgium              1054
Channel Islands       906
Name: count, dtype: int64

In [47]:
print("Total unique customers:", online_retail_store_df['Customer ID'].nunique())
print("Rows with no Customer ID:", online_retail_store_df['Customer ID'].isna().sum())

Total unique customers: 4383
Rows with no Customer ID: 107927

In [48]:
first_seen = online_retail_store_df.dropna(subset=['Customer ID']).groupby('Customer ID')['InvoiceDate'].min()
first_seen.dt.year.value_counts()

InvoiceDate
2010    3338
2009    1045
Name: count, dtype: int64

In [49]:
dupes = online_retail_store_df[online_retail_store_df.duplicated(keep=False)]
print(dupes.shape)
dupes.head(4)

(13283, 8)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom

In [ ]:
true_duplicates = online_retail_store_df[online_retail_store_df.duplicated(subset=['Invoice', 'StockCode', 'InvoiceDate'], keep=False)]
print(true_duplicates.shape)

(25393, 8)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
289,489488,22125,UNION JACK HOT WATER BOTTLE,2,2009-12-01 10:59:00,5.95,17238.0,United Kingdom
299,489488,22125,UNION JACK HOT WATER BOTTLE,1,2009-12-01 10:59:00,5.95,17238.0,United Kingdom
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
372,489517,21791,VINTAGE HEADS AND TAILS CARD GAME,6,2009-12-01 11:34:00,1.25,16329.0,United Kingdom
373,489517,21790,VINTAGE SNAP CARDS,4,2009-12-01 11:34:00,0.85,16329.0,United Kingdom

In [5]:
# True duplicates - all fields identical
true_dupes = online_retail_store_df[
    online_retail_store_df.duplicated(
        subset=['Invoice', 'StockCode', 'InvoiceDate', 'Quantity'], 
        keep=False
    )
]
print(true_dupes.shape)

# Conflicting records - same key, different quantity
conflicting = online_retail_store_df[
    online_retail_store_df.duplicated(
        subset=['Invoice', 'StockCode', 'InvoiceDate'], 
        keep=False
    )
] 
conflicting_diff_qty = conflicting[
    conflicting.duplicated(subset=['Invoice', 'StockCode', 'InvoiceDate', 'Quantity'], keep=False) == False
]
print(conflicting_diff_qty.shape)

(13485, 8)
(11908, 8)

In [10]:
true_dupes[true_dupes['Invoice']==489517]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
388,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom

In [11]:
online_retail_store_df[online_retail_store_df['Invoice']==489517]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
361,489517,21705,BAG 500g SWIRLY MARBLES,1,2009-12-01 11:34:00,1.65,16329.0,United Kingdom
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
364,489517,16207A,PINK STRAWBERRY HANDBAG,2,2009-12-01 11:34:00,2.95,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
366,489517,85123A,WHITE HANGING HEART T-LIGHT HOLDER,1,2009-12-01 11:34:00,2.95,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
369,489517,21584,RETRO SPOT SMALL TUBE MATCHES,20,2009-12-01 11:34:00,1.65,16329.0,United Kingdom
370,489517,20972,PINK CREAM FELT CRAFT TRINKET BOX,1,2009-12-01 11:34:00,1.25,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
372,489517,21791,VINTAGE HEADS AND TAILS CARD GAME,6,2009-12-01 11:34:00,1.25,16329.0,United Kingdom
373,489517,21790,VINTAGE SNAP CARDS,4,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
374,489517,21931,JUMBO STORAGE BAG SUKI,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
375,489517,20711,JUMBO BAG TOYS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
376,489517,47591A,CAROUSEL DES CHILD'S APRON,1,2009-12-01 11:34:00,1.65,16329.0,United Kingdom
377,489517,84997B,RED 3 PIECE MINI DOTS CUTLERY SET,12,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
378,489517,84997A,GREEN 3 PIECE MINI DOTS CUTLERY SET,12,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
380,489517,22122,SET OF 2 FANCY FONT TEA TOWELS,12,2009-12-01 11:34:00,2.95,16329.0,United Kingdom
381,489517,20971,PINK BLUE FELT CRAFT TRINKET BOX,1,2009-12-01 11:34:00,1.25,16329.0,United Kingdom
382,489517,21252,SET OF MEADOW FLOWER STICKERS,1,2009-12-01 11:34:00,2.95,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
387,489517,21837,CROSS STITCH ALPHABET CUSHION COVER,2,2009-12-01 11:34:00,5.95,16329.0,United Kingdom
388,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
389,489517,22335,HEART DECORATION PAINTED ZINC,1,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
392,489517,21791,VINTAGE HEADS AND TAILS CARD GAME,1,2009-12-01 11:34:00,1.25,16329.0,United Kingdom
393,489517,21790,VINTAGE SNAP CARDS,1,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
395,489517,85129A,"WHITE PEARL BEADED HEART, SMALL",1,2009-12-01 11:34:00,1.25,16329.0,United Kingdom
396,489517,84791,GINGHAM HEART DECORATION,1,2009-12-01 11:34:00,2.95,16329.0,United Kingdom
397,489517,21244,BLUE SPOTTY PLATE,4,2009-12-01 11:34:00,1.69,16329.0,United Kingdom
398,489517,20675,BLUE SPOTTY BOWL,4,2009-12-01 11:34:00,1.25,16329.0,United Kingdom

In [50]:
dupes['InvoiceDate'].dt.year.value_counts()

InvoiceDate
2010    12306
2009      977
Name: count, dtype: int64